/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer_access;

import java.awt.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author danpiamonte
 */
public final class Step2 extends javax.swing.JFrame {

    /**
     * Creates new form Step2
     */
    private OrderList orderList = new OrderList();
    private JPanel allOrders = new JPanel();
    private float subtotal = 0;

    int orderNum;
    int tableNum;

    public Step2() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public Step2(OrderList orderList, int tableNum) {
        this.tableNum = tableNum;
        allOrders = new JPanel();
        initComponents();
        this.setLocationRelativeTo(null);
        this.orderList = orderList;
        orderContainer.add(addScrollPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PrevButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        orderContainer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 600));
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(166, 206, 57));
        jPanel1.setMaximumSize(new java.awt.Dimension(920, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(920, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 600));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setText("STEP 4");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("BILL OUT");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setText("STEP 3");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("ORDER PROCESSING");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SUMMARY OF ORDERS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("STEP 2");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("CHOOSE ORDER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer_access/images/logo@2x.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, 64));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("STEP 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer_access/images/step2.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        PrevButton.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        PrevButton.setText("< PREV");
        PrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PrevButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 90, 50));

        NextButton.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        NextButton.setText("NEXT >");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(NextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 90, 50));

        orderContainer.setBackground(new java.awt.Color(166, 206, 57));
        orderContainer.setAutoscrolls(true);
        orderContainer.setMaximumSize(new java.awt.Dimension(770, 310));
        orderContainer.setMinimumSize(new java.awt.Dimension(770, 310));
        orderContainer.setPreferredSize(new java.awt.Dimension(770, 310));
        orderContainer.setRequestFocusEnabled(false);
        jPanel1.add(orderContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 770, 310));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("QUANTITY");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PRODUCT ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("PRICE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("PRODUCT NAME");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        getContentPane().setBackground(new Color(166, 206, 57));
    }//GEN-LAST:event_jPanel1ComponentShown

    private void PrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Step1(this.orderList).setVisible(true);

    }//GEN-LAST:event_PrevButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        finalList finalOrder = new finalList();
        ArrayList<finalOrder> temp = new ArrayList();
        String ID = null;
        String name = null;
        float price = 0;
        int qty = 0;

        Component[] child = orderContainer.getComponents();
        for (int i = 0; i < child.length; i++) {
            System.out.println("CHILDREN OF ORDERCONTAINER: " + child[i].toString());
            if (child[i] instanceof JScrollPane) {
                Component[] scroll = ((JScrollPane) child[i]).getViewport().getComponents();
                for (int j = 0; j < scroll.length; j++) {
                    System.out.println("CHILDREN OF SCROLLPANE:" + scroll[j]);
                    if (scroll[j] instanceof JPanel) {
                        Component[] insideScroll = ((JPanel) scroll[j]).getComponents();
                        for (int k = 0; k < insideScroll.length; k++) {
                            System.out.println("INSIDE SCROLL: " + insideScroll[k]);
                            if (insideScroll[k] instanceof JPanel) {
                                Component[] labels = ((JPanel) insideScroll[k]).getComponents();
                                for (int l = 0; l < labels.length; l++) {
                                    System.out.println("ORDER PANELS: " + labels[l].toString());
                                    ID = ((JLabel) labels[0]).getText();
                                    name = ((JLabel) labels[1]).getText();
                                    price = Float.valueOf(((JLabel) labels[2]).getText());
                                    qty = Integer.parseInt(((JComboBox) labels[3]).getSelectedItem().toString());
                                }
                                System.out.println("QTY: "+ qty);
                                temp.add(new finalOrder(ID, qty));
                                finalOrder.addOrder(temp); 
                            }
                        }
                    }
                }
            }
        }     
       
        displayOrder(finalOrder);
        this.setVisible(false);
        try {
            new Step3(orderNum, tableNum).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Step2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NextButtonActionPerformed


    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown
    public void displayOrder(finalList finalOrders) {
        Query query = new Query();
        Connection con = query.getConnection();
        PreparedStatement pstmt;
        ResultSet rs;
        for (int i = 0; i < finalOrders.getFinalList().size(); i++) {
            System.out.print(" " + i + " ");
            System.out.print(finalOrders.getFinalList().get(i).getProdID() + " ");
            System.out.println(" " + finalOrders.getFinalList().get(i).getQuantity());
            System.out.println("qty");
            int qtyLeft = query.getQuantity(finalOrders.getFinalList().get(i).getProdID());
            int quantityLeft = qtyLeft - finalOrders.getFinalList().get(i).getQuantity();
            query.updateQuantity(quantityLeft, finalOrders.getFinalList().get(i).getProdID());
        }

        

        try {
            pstmt = con.prepareStatement("SELECT MAX( orderNum ) AS id FROM orders");
            rs = query.myExecuteQuery(pstmt);
            System.out.println("orderNum:");
            if (!rs.next()) {
                orderNum = 1;
            } else {
                orderNum = rs.getInt("id");
                orderNum++;
            }
            System.out.println(orderNum);
            query.insertOrder(orderNum, tableNum);
            query.insertOrderdetails(finalOrders, orderNum, tableNum);
        } catch (SQLException ex) {
            Logger.getLogger(Step2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Component panelOrder(OrderList orders, int ndx) {
        JPanel order = new JPanel();
        order.setLayout(new GridLayout(0, 5));
        order.setBackground(new Color(166, 206, 57));

        JLabel prodID = new JLabel();
        JLabel prodName = new JLabel();
        JLabel prodPrice = new JLabel();
        JComboBox qty = new JComboBox();
        JButton del = new JButton("Remove");

        prodID.setText(orders.getOrderList().get(ndx).getProdID());
        prodName.setText(orders.getOrderList().get(ndx).getProdName());
        prodPrice.setText(Float.toString(orders.getOrderList().get(ndx).getPrice()));

        prodPrice.setHorizontalAlignment(JLabel.CENTER);
        prodName.setHorizontalAlignment(JLabel.CENTER);
        prodID.setHorizontalAlignment(JLabel.CENTER);

        prodID.setMaximumSize(new Dimension(150, 20));
        prodID.setMinimumSize(new Dimension(150, 20));
        prodID.setPreferredSize(new Dimension(150, 20));
        prodPrice.setMaximumSize(new Dimension(150, 20));
        prodPrice.setMinimumSize(new Dimension(150, 20));
        prodPrice.setPreferredSize(new Dimension(150, 20));
        prodName.setMaximumSize(new Dimension(150, 20));
        prodName.setMinimumSize(new Dimension(150, 20));
        prodName.setPreferredSize(new Dimension(150, 20));
        qty.setMaximumSize(new Dimension(50, 20));
        qty.setMinimumSize(new Dimension(50, 20));
        qty.setPreferredSize(new Dimension(50, 20));

        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int reply = JOptionPane.showConfirmDialog(null, "Are you sure?", "REMOVE ORDER", JOptionPane.YES_NO_OPTION);

                if (reply == JOptionPane.YES_OPTION) {
                    orderContainer.revalidate();
                    orderContainer.repaint();
                    orderContainer.removeAll();
                    new OrderList().removeOrder(orders.getOrderList().get(ndx).getProdID(), orderList);
                    for (int i = 0; i < orderList.getOrderList().size(); i++) {
                        System.out.println(orderList.getOrderList().get(i).getProdID());
                        orderContainer.add(addScrollPane());
                    }
                }
            }
        });

        order.add(prodID);
        order.add(prodName);
        order.add(prodPrice);
        order.add(qty);
        order.add(del);

        int max = orders.getOrderList().get(ndx).getQtyInStock();
        max++;
        System.out.println("max num " + max);
        for (int i = 1; i < max; i++) {
            qty.addItem(i);
        }

        //    pane.add(order);
        return order;
    }

    public Component addScrollPane() {

        JScrollPane scrollPane = new JScrollPane(allOrders);
        scrollPane.setPreferredSize(new Dimension(770, 310));
        scrollPane.setMinimumSize(new Dimension(770, 310));
        scrollPane.setMaximumSize(new Dimension(770, 310));
        allOrders.revalidate();
        allOrders.repaint();
        allOrders.removeAll();
        scrollPane.getViewport().setBackground(new Color(166, 206, 57));
        for (int i = 0; i < this.orderList.getOrderList().size(); i++) {
            allOrders.add(panelOrder(this.orderList, i));           
        }
        allOrders.setPreferredSize(new Dimension(600, 360));
        allOrders.setMinimumSize(new Dimension(600, 360));
        allOrders.setMaximumSize(new Dimension(600, 360));
        allOrders.setBackground(new Color(166, 206, 57));

        return scrollPane;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Step2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Step2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Step2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Step2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Step2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JButton PrevButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel orderContainer;
    // End of variables declaration//GEN-END:variables
}
