/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer_access;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author danpiamonte
 */
public class Step4 extends javax.swing.JFrame {

    /**
     * Creates new form Step4
     */
    
    int orderNum = 0;
    int tableNum;
    ArrayList<Order> receipt = new ArrayList();
    
    public Step4() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Step4(int orderNum, int tableNum) throws SQLException {
        this.tableNum = tableNum;
        initComponents();
        this.setLocationRelativeTo(null);
        this.orderNum = orderNum;
        getReceipt();
        addSubTotal();
    }
    
    JPanel rDetails = new JPanel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        billOut = new javax.swing.JButton();
        receiptContainer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        subTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(166, 206, 57));
        jPanel1.setMaximumSize(new java.awt.Dimension(920, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(920, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 600));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("STEP 4");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("BILL OUT");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setText("STEP 3");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("ORDER PROCESSING");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("SUMMARY OF ORDERS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setText("STEP 2");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("CHOOSE ORDER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer_access/images/logo@2x.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, 64));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("STEP 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer_access/images/step4.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        billOut.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        billOut.setText("READY TO BILL OUT >");
        billOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billOutActionPerformed(evt);
            }
        });
        jPanel1.add(billOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 220, 50));

        receiptContainer.setBackground(new java.awt.Color(166, 206, 57));
        receiptContainer.setMaximumSize(new java.awt.Dimension(630, 330));
        receiptContainer.setMinimumSize(new java.awt.Dimension(630, 330));
        receiptContainer.setPreferredSize(new java.awt.Dimension(630, 330));
        jPanel1.add(receiptContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 630, 330));

        jLabel9.setFont(new java.awt.Font("Source Sans Pro Light", 1, 18)); // NOI18N
        jLabel9.setText("SUBTOTAL:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, 50));

        subTotal.setFont(new java.awt.Font("Source Sans Pro Light", 1, 14)); // NOI18N
        subTotal.setText("PHP ");
        jPanel1.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getReceipt() throws SQLException{
        Query q = new Query();
        ResultSet rs = q.getMyOrders(orderNum);
        
        ArrayList<Order> orders = new ArrayList();
        
        while(rs.next()){
            orders.add(new Order(rs.getString("productId"), rs.getString("productName") ,rs.getInt("quantity"), 0 ,rs.getFloat("price")));
        }
        
        displayReceipt(orders);
    }
    
    public void displayReceipt(ArrayList<Order> orders){
        this.receipt = orders;
        receiptContainer.add(addScrollPane());      
    }
    
    public Component addScrollPane() {
        JScrollPane scrollPane = new JScrollPane(rDetails,
                JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,
                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setPreferredSize(new Dimension(630,330));
        scrollPane.setMinimumSize(new Dimension(630,330));
        scrollPane.setMaximumSize(new Dimension(630,330));
        for (int i = 0; i < receipt.size(); i++) {
            rDetails.add(panelOrder(i));
        }

        rDetails.setPreferredSize(new Dimension(630,330));
        rDetails.setMinimumSize(new Dimension(630,330));
        rDetails.setMaximumSize(new Dimension(630,330));

        return scrollPane;
    }
    
     public Component panelOrder(int ndx) {
        JPanel order = new JPanel();
        order.setLayout(new GridLayout(0, 4));
        JLabel prodName = new JLabel();
        JLabel prodQty = new JLabel();
        JLabel prodPrice = new JLabel();
        JLabel prodPartial = new JLabel();

        prodName.setText(receipt.get(ndx).getProdName());
        prodQty.setText(Integer.toString(receipt.get(ndx).getQuantity()));
        prodPrice.setText(Float.toString(receipt.get(ndx).getPrice()));
        float subtotal = receipt.get(ndx).getPrice() * receipt.get(ndx).getQuantity();
        prodPartial.setText(Float.toString(subtotal));

        prodName.setMaximumSize(new Dimension(121, 20));
        prodName.setMinimumSize(new Dimension(121, 20));
        prodName.setPreferredSize(new Dimension(121, 20));
        prodQty.setMaximumSize(new Dimension(121, 20));
        prodQty.setMinimumSize(new Dimension(121, 20));
        prodQty.setPreferredSize(new Dimension(121, 20));
        prodPrice.setMaximumSize(new Dimension(121, 20));
        prodPrice.setMinimumSize(new Dimension(121, 20));
        prodPrice.setPreferredSize(new Dimension(121, 20));

        order.add(prodName);
        order.add(prodQty);
        order.add(prodPrice);
        order.add(prodPartial);
        return order;
    }
    
    public void addSubTotal(){
        float total = 0;
        for(int i = 0; i < receipt.size(); i++){
         total += receipt.get(i).getQuantity() * receipt.get(i).getPrice();
        }
        
        subTotal.setText(String.format("PHP %,.2f", total));
    }
    
    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        getContentPane().setBackground(new Color(166,206,57));
    }//GEN-LAST:event_jPanel1ComponentShown

    private void billOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billOutActionPerformed
        // TODO add your handling code here:
        
        Query query = new Query();
        query.updateBillout(tableNum, orderNum);

        int reply = JOptionPane.showConfirmDialog(null,"Thank you for eating with us!","BILL OUT",JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE);
              
        if (reply == JOptionPane.OK_OPTION){
            this.setVisible(false);
            new Step1().setVisible(true);
        }
    }//GEN-LAST:event_billOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Step4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Step4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Step4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Step4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Step4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel receiptContainer;
    private javax.swing.JLabel subTotal;
    // End of variables declaration//GEN-END:variables
}
